dist: trusty
sudo: false
git:
  # use depth 2 just in case two refs get pushed at once (like a tag)
  depth: 2
language: ruby
cache:
  bundler: true
  directories:
  - .cache
rvm:
- 2.5.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
#install:
## we can't rely on the bundler that comes with Ruby/rvm
#- gem install bundler
#- bundle --path=.bundle/gems
script:
- bundle exec rake pr
# html-proofer takes more than 20 minutes, so it can't be used in CI
#- travis_wait bundle exec rake validate
